server:
  port: 6789
spring:
  datasource:
      url: jdbc:mysql://localhost/dbdoc?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&tinyInt1isBit=false
      username: root
      password: rootroot
  freemarker:
    prefer-file-system-access: false